test auto generate documentation

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -40,10 +40,8 @@ jobs:
         name: commit documentation changes if any
         run: |
           if  [[ $(if [[ -n "$(git status --porcelain)" ]]; then echo "true"; else echo "false"; fi) == "true" ]]; then
-            git config user.name github-actions
-            git config user.email github-actions@github.com
-            git commit -a -m "Documentation generated"
-            git push
+            echo "\n ERROR: check in documentation changes"
+            exit 1
           else 
             echo "\n++No Changes to Documentation++\n"
           fi
