test auto generate documentation

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -7,6 +7,10 @@ on:
 jobs:
   run_tests:
     runs-on: ubuntu-latest
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the
+      # added or changed files to the repository.
+      contents: write
     steps:
       -
         name: Checkout
@@ -33,13 +37,14 @@ jobs:
         name: Generate Documentation
         run: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs generate --provider-name terraform-provider-banyan --examples-dir ./examples/
       -
-        name: check in documentation
-        uses: actions/checkout@v4
+        name: commit documentation changes if any
         run: |
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git commit -m "documentation generated"
-          git push
+          if  [[ $(if [[ -n "$(git status --porcelain)" ]]; then echo "true"; else echo "false"; fi) == "true" ]]; then
+            echo "\n ERROR: check in documentation changes"
+            exit 1
+          else 
+            echo "\n++No Changes to Documentation++\n"
+          fi
       -
         name: Static Check
         uses: dominikh/staticcheck-action@v1.3.0
