fix incorrect document usage for data block (#144) (#146)
* incorrect document usage fix for data block

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -7,10 +7,14 @@ on:
 jobs:
   run_tests:
     runs-on: ubuntu-latest
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the
+      # added or changed files to the repository.
+      contents: write
     steps:
       -
         name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       -
         name: Unshallow
         run: git fetch --prune --unshallow
@@ -29,6 +33,18 @@ jobs:
           TF_ACC: true
           BANYAN_API_KEY: ${{ secrets.BANYAN_API_KEY }}
           BANYAN_HOST: ${{ secrets.BANYAN_HOST }}
+      -
+        name: Generate Documentation
+        run: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs generate --provider-name terraform-provider-banyan --examples-dir ./examples/
+      -
+        name: commit documentation changes if any
+        run: |
+          if  [[ $(if [[ -n "$(git status --porcelain)" ]]; then echo "true"; else echo "false"; fi) == "true" ]]; then
+            echo "\n ERROR: check in documentation changes"
+            exit 1
+          else 
+            echo "\n++No Changes to Documentation++\n"
+          fi
       -
         name: Static Check
         uses: dominikh/staticcheck-action@v1.3.0
